version: '3.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: es-container
    environment:
      - node.name=es01
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    ports:
      - 5601:5601
    networks:
      - es-net
    depends_on:
      - elasticsearch

volumes:
  data01:
    driver: local
networks:
  es-net:
    driver: bridge